language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

script:
    - cargo build --verbose
    - cargo test --verbose

env:
    global:
        - secure: "YU+o1BvxT5/Uh1JRtQbbpJgIT+slZ/WhhoMgl3I1COpScklpAb9XLGuu9ptF4iucpKKZfATqmOI6vx6qjvzDRdYypK9RA8wDCiR7tz68T4EiewAINBogcgthw3QVNuqAdV0k3Jj2Itw4AXQojV5wIADHxs5t//6Yndt+WRTN+29kOmRDDWMo+iBMJ0oFpQD9t7fg8puiPCRRIB8NPFpZH3FPt31EGikyDHaDIlE5T2MMdxJh0tudYRfznfGkXHVy2hTsKW15eJKLUSW3EKKFgH+quptuTQTi7oG+R/mH488lzZExshPgH0eSGUOf+D71ls3dV56/zg/stCX+52TcCnewcifdIawalH/NyFlBu6sGKmBB3VZLBB7sJgdumhNmZaN/Hjv7Vjs8DeCdMpA1H1Y5nPZGtIbNoFpC3A15aRpDS/TwR5xzJYH7Y0XSwhZiGA7sM2XaoBg1CPDrtPspEXDLSmafGhUEFstmLp37/Hs2/N2+LMwXNrkhcsbT95apH1PrcVf62sEe1yQgnekkz3ya5Siuc9Ow2ERP8zV1/lF42MHYMuzWO4YYI4Dh6+wPiejr0ZeRGdcQ0Prd9kQTPEhE66Jh768eer2EHVUOQb9n0+AnOgGQTyUR3+Tzoiusm7igtREojAbXdHarmQWgzHIhHJ5etVfYe8HKFJouVcE="
        - secure: "GUuHPhbuFkUF0MkfW0gsS5Eun1x1z/WQa79+0POPG6bi0I7hCNV8m3kloC9PWXc2ygp/xSfexzCOu1wOPNQBsI/UqtCJpLKGwo7R0xCgWgZQzc5d7UIhRyAXNCUEsCkKK2f8lQStBWz2iI48jgRa/mtNnPcC5ZoTk64iEe+0Y6XCVD36nVstakWoXr2IYWOMJmyGSgYZy5aQdWtT5x3MKmz2/tW2yS2V4HF5mOYxMPgMC0hPoS/ZYmHiaTyQ2ejkH9eUwPBKHOLRn/yQNpu1NULoom3YrwBEHmqthIRjfIE++rWCG9pirsoQRCfj53F3bH5cPQHg5LrXFBGqg1FO7LbYuheigKvkUpF9VA+J4Pf7nb8WNJ6wrZAXniqCPlK5TOnrLxLtVlbcWfF/VVqixT7tDQDCT/+mboMTWC4JURlgVYBxcjSdj3hD6+SpUCYYbrj68ZvA/Q23LYDa06uFVwlqqBP3nVeM6sHOIFCw0E4Gxxm0zgosTEChonoZo5rkg8d+Cf/Z6mWm2aOuEkWGiGeXioCRxzM+cMXBDDkT24qidCg1et+buH+do5FpEI1JCqYuTuqqY6quwUngmwDZaqSlwh9Q2Alhpi3VzVlXiuJc9Mi3nxayuyCkIeYkRKJclLD/+piZ6en9S/HAsiQBWOdTjrL7zG8FweHwvCegCv0="
